### ISSUE TITLE
PPP flag

### ISSUE THREAD

**Issue by FIAV1** [ppp-project/ppp#249]
Hi there, I have a question about the functioning of this module. I saw from logs that the PPP flag sequence (0x7e) is not always added at the beginning of the PPP packet. Is it possible to enforce this to happen, through an option from the command line or some simple modification to the code? I have a server that discard all packets that dont start with it, so I can barely connect to it... Thanks in advance!

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by paulusmack** [comment]
Your server is buggy, then, since rfc1331is quite clear that the flag character is a separator and only one flag is required between two frames.

In fact the decision about whether to put the flag at the beginning of the packet is made in the kernel driver, not pppd, at least on Linux (you don't say what OS you're using). The ppp_async module in Linux has a timeout that defaults to 1 second; if the previous packet was transmitted less than this amount of time before the current packet, the flag is omitted. You can set the timeout to 0 by putting flag_time=0 in the options for the ppp_async module, and then it should always transmit the flag.

**Comment by FIAV1** [comment]
> Your server is buggy, then, since rfc1331is quite clear that the flag character is a separator and only one flag is required between two frames.
> 
> In fact the decision about whether to put the flag at the beginning of the packet is made in the kernel driver, not pppd, at least on Linux (you don't say what OS you're using). The ppp_async module in Linux has a timeout that defaults to 1 second; if the previous packet was transmitted less than this amount of time before the current packet, the flag is omitted. You can set the timeout to 0 by putting flag_time=0 in the options for the ppp_async module, and then it should always transmit the flag.

Yes, I did this way applying this simple patch to Linux Kernel and it all worked like a charm. Maybe I should add a pull request to linux kernel, exposing this feature as an option, so if anyone would need it it will have it.

Thanks guys, I'll close this!

**Comment by Neustradamus** [comment]
@FIAV1: Please inform us when you will publish a patch to Linux Kernel and post the link here ^^

**Comment by FIAV1** [comment]
I'm reopening this, since I found out that ppp flag is a module parameter, so I suspect it can be set from the outside. I'm trying to understand how, if you can help me in this process I post here the relevant code line from linux kernel:
https://github.com/torvalds/linux/blob/master/drivers/net/ppp/ppp_async.c#L88

From what I found out untill now, something like `./insmod ppp-async.ko flag_time=0` can be used to set this, but I don't know how to transform this in an option usable from `options` file.

**Comment by FIAV1** [comment]
Some updates: I managed to make this work by manually loading the `ppp_async` kernel module passing the `flag_time=0` parameter to it, like this:

```bash
sudo modprobe ppp_async flag_time=0
```

This could be obviously much easier if it can be converted to an `options` option, something like `FLAG_TIME` that can be set to an integer, then pppd takes care of loading it.

Again, I can do that, but I need some help to understand from where to start 😁

**Comment by paulusmack** [comment]
I really don't think it is pppd's job to load the kernel modules, particularly since there are other system components that already do that. If you want to have the flag_time parameter applied automatically then you could create a /etc/modprobe.d/ppp_async.conf file containing the line:

options ppp_async flag_time=0

Having pppd set a module option wouldn't work if the module was already loaded, or if you had multiple instances of pppd where one was given a flag_time=0 option and the other wasn't.
