### ISSUE TITLE
interposed functions in sha1.h

### ISSUE THREAD

**Issue by rustylife** [ppp-project/ppp#265]
ppp code has 3 functions globally defined in sha1.h that interpose openssl library functions
i noticed this while trying to debug HMAC() function failure with EVP_sha1() for #128 
openssl function HMAC() calls HMAC_Init_ex(), which then calls SHA1_Init() and SHA1_Update() functions from ppp code instead of  proper function from openssl library
there are multiple ways to go about fixing this, but first i would like to get your opinion and feedback on how you would like to get it fixed

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

cc: @enaess, @jjkeijser, @tisj, @pali?

**Comment by enaess** [comment]
Makefile.linux defines OPENSSL if USE_SRP is configured (and is not enabled on Linux). USE_EAPTLS also depends openssl but only specifies -lssl ... Seems like some options needs better definitions. If we link with openssl, then there is no need to link with the internal sha1.h/c. 

IMO the makefile needs some cleaning up.

**Comment by jjkeijser** [comment]
if you look closer you will see that the Makefile contains
  NEEDCRYPTOLIB = y
and later on that says

ifdef NEEDCRYPTOLIB
  LIBS     += -lcrypto
endif

this was done to avoid linking in '-lcrypto' multiple times. The same could be applied to the 'ifdef USE_SRP' part. However, I did not touch that part of the code and hence I also did not touch the Makefile part.

As for the sha1 functions:  I had a patch once to replace all md5+sha1 code with the OpenSSL versions but that patch was excluded from my EAP-TLs patch. You could also consider replacing the (ancient) md5 code but what would we gain?  the md4/md5/sha1 functions comprise 31kb, so it's not *that* much code to swap out.

**Comment by tisj** [comment]
Bear in mind that embedded platforms like to keep dependencies minimal, and openssl is a big library. Operating systems like OpenWRT mostly use ppp for internet connectivity, and therefore don't need fancy stuff like TLS or SRP. Moreover they offer a choice in what SSL library to use for your system, such as mbedtls, ustream-ssl, wolfssl, .. and openssl.

If compatibility with openssl is an issue, I would propose to either rename (prefix) the internal crypto stuff (eg. PPP_SHA_Init) as a simple resolution, or as a bigger/modular approach make generic abstractions to support different crypto implementations, so that you can choose which one to use at build time (internal, openssl, other ssl libraries...)

**Comment by jjkeijser** [comment]
I agree that it should remain possible to build ppp *without* using OpenSSL.  That's why I added the 
  EAP_TLS=y
flag to the pppd Makefile - if you disable TLS and SRP then the code should still build without linking in OpenSSL (depending on the platform; you *do* need the `crypt()` function, IIRC).

I'd not rename the internal MD5/SHA stuff for this, I'd simply make sure that the code builds & works as expected either with the internal functions or when using the OpenSSL library routines (and no, support for mbedtls, ustream-ssl  or wolfstream are not on my TODO or wishlist).

**Comment by Neustradamus** [comment]
@ all: Any news on it?

**Comment by Neustradamus** [comment]
@ all: Any news about it?

**Comment by enaess** [comment]
Still working on it.

**Comment by enaess** [comment]
@Neustradamus @rustylife could we close this issue now?

**Comment by enaess** [comment]
@paulusmack
