### ISSUE TITLE
How can I redirect pptp-server's tcp traffic to redsocks?

### ISSUE THREAD

**Issue by LaiZhou** [ppp-project/ppp#277]
Let's say I have a pptp client conneced to the pptp server(port:1723).
And the redsocks is listening on 12345, that can proxy tcp traffic to socks5 proxy.
Now ,how can I redirect pptp-server's tcp traffic to redsocks?
```
iptables -A OUTPUT -o ppp+ -p tcp -j REDIRECT --to 12345

```

but it doesn't work.

**Comment by enaess** [comment]
@LaiZhou I am not sure anyone would understand what you are trying to do here. Are you trying to proxy all PPTP traffic via a SOCKS5 proxy? In case, you are off in the weeds because the TCP:1723 is only used as a control protocol to establish a GRE tunnel between the two peers. GRE is a different protocol like TCP and UDP is two other protocols, (GRE != TCP|UDP).

PPTP is inherently insecure. Apple discontinued support for the protocol years ago. You should probably have a look at setting up a SSTP tunnel instead. If you look at the sstp-client and network-manager-sstp implementation on Linux, it does support a Web-Proxy configuration.

**Comment by LaiZhou** [comment]
ok, I'll try l2tp .
