### ISSUE TITLE
PPP 2.4.1/PPP 2.4.9 Connection Problem

### ISSUE THREAD

**Issue by Discovery00** [ppp-project/ppp#340]
Hello to everyone,
My Netgear D7000 modem can no longer connect to the internet. My internet service provider replaced the SSG device with ZTE. I care about your opinions. Because of this problem, we ported PPPD 2.4.9 to the device. The same problem still persists. I am attaching screenshots of Netgear source codes causing this issue. Thank you for your help.
![157993258-5aaf8534-40d4-4ba5-9822-95b340376afa](https://user-images.githubusercontent.com/100864172/163645397-b682a159-c7de-4124-9f70-2e8a6d8472f0.png)
![157992409-ab2f8875-12d0-4779-9103-a7bcca9f3317](https://user-images.githubusercontent.com/100864172/163645421-3e0e5f62-3400-4ad5-a62d-714ee7e14a6f.png)
![157992393-673bb42b-b147-4122-ab3c-3313df56dd2d](https://user-images.githubusercontent.com/100864172/163645437-112b01b7-dca2-4b18-8af1-258959b9e59d.png)
[PPP_Log.pdf](https://github.com/ppp-project/ppp/files/8498459/PPP_Log.pdf)

**Comment by Discovery00** [comment]
PPPD 2.4.9 Log File
[PPP_Log.pdf](https://github.com/ppp-project/ppp/files/8498464/PPP_Log.pdf)

**Comment by enaess** [comment]
@pali Does this look reasonable? 

@Discovery00 - You should be able to open a Pull Request against the ppp/master branch and sign off the code. You able to do this?

**Comment by Neustradamus** [comment]
@Discovery00: Have you seen the @enaess comment?

**Comment by Neustradamus** [comment]
@enaess: It has been solved?
If not, can you look it?

**Comment by paulusmack** [comment]
It's not clear whether the code posted is being proposed for inclusion, or if not, what exactly is going on.

If there is a need to connect to a specific access concentrator, then the pppoe-ac, pppoe-mac or pppoe-service options may help.

Otherwise all I can see in the logs supplied is that several attempts to connect are made, and on each attempt we get 3 configure-requests but never respond. It's unclear why. I don't know whether the logs are from a server/access concentrator or from a client.

**Comment by paulusmack** [comment]
Closing because no response from submitter for 2 years.
