### ISSUE TITLE
Cannot get verbose output because “debug” & “-detach” options have no effect.

### ISSUE THREAD

**Issue by bruceleerabbit** [ppp-project/ppp#352]
These options are supplied in /etc/ppp/options:
* debug
* -detach
* nodetach

The ppp logging is no more verbose than without those options. They seem to take no effect. This is the output I see either way after successfully connecting with `wvdial`:

/var/log/messages:
```
$timestamp $host pppd[84797]: pppd 2.4.9 started by $user, uid 0
$timestamp $host pppd[84797]: Using interface ppp0
$timestamp $host pppd[84797]: Connect: ppp0 <--> /dev/ttyUSB0
$timestamp $host pppd[84797]: LCP: timeout sending Config-Requests
$timestamp $host pppd[84797]: Connection terminated.
$timestamp $host pppd[84797]: Modem hangup
$timestamp $host pppd[84797]: Exit.
```

Certainly some people get more verbosity than that because I see posts showing more verbosity, like the output in this bug report: https://github.com/ppp-project/ppp/issues/310

I suspected I was encountering this bug from 2011:

  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=639368

But I think that bug is different because Beraldo Costa Leal gets just one line of output (not even the standard output).

**Comment by paulusmack** [comment]
You don't need both -detach and nodetach, they are synonyms. Make sure the debug and nodetach options aren't on a line that starts with '#', since anything following a '#' is ignored as a comment.

You can use the "dump" option to see what options pppd has in effect and where they were set.

If you can't get it to work, post the contents of your /etc/ppp/options and any other options file you are using.

**Comment by Neustradamus** [comment]
@bruceleerabbit: Have you seen the @paulusmack comment?

**Comment by bobbyl140** [comment]
I'm having this issue when invoking pppd with mgetty, for dialing in with a modem. I tried putting "nodetach" both in the config file, and directly in the invocation. Using the `ppp` package version 2.4.9 from the Rocky Linux 9 baseos repo. 

The reasonng here for nodetach is, when mgetty gets control back from the process it calls, it assumes said process ended. I need `pppd` to stay in the foreground because of this. I talked to the developer of mgetty about this and he told me to use nodetach, but even with that it's still happening.

**Comment by Neustradamus** [comment]
@bruceleerabbit: Have you seen the @paulusmack comment?

**Comment by Neustradamus** [comment]
@bruceleerabbit: Have you seen the @paulusmack comment?

**Comment by paulusmack** [comment]
Closing based on lack of activity.
