### ISSUE TITLE
EAP-TLS automatic downgrade on unsupported/restricted versions

### ISSUE THREAD

**Issue by Evengard** [ppp-project/ppp#385]
Hello!

For some reason, if a TLS version offered by the client is higher (or even unknown, in case of old PPP builds without TLS 1.3 version support), PPP just fails the EAP-TLS handshake. This is a bit strange, as most clients actually allows a fallback to a lower TLS version without any problems (which is actually seen worldwide in the case of, for example, HTTPS - HTTPS servers supporting TLS 1.3 are accepting (older) TLS 1.2 clients without problems, just downgrading the handshake to 1.2 instead).

Would it be possible to apply a similar fallback mechanism here too (up to the one specified in `max-tls-version`, for example), instead of just erroring out?

**Comment by Neustradamus** [comment]
@jjkeijser: Have you seen this ticket?

**Comment by jjkeijser** [comment]
This is exactly how the (stock) ppp 2.4.9 code currently works - the client and server negotiate the best TLS version based on what both sides offer. If the ppp-based server only supports TLS 1.0 , then the negotiation will end up with TLS 1.0 regardless of the TLS proposal made by the client. I tested this with a ppp 2.4.9 client versus a ppp 2.4.9 server.

Without more information about exactly which version of pppd is being used (patched by the distro maintainers?) , it is impossible to tell what is failing here. 
Also, follow the instructions on https://jjkeijser.github.io/ppp/doc_pptp_serversetup.html and add
```
  debug
  logfile /tmp/pppd.log
```

to the `pptpd-options` file (or equivalent) for debug output - from that I can usually tell what is happening during the TLS handshake.

**Comment by Evengard** [comment]
Was it changed? I'll retest it in coming days, was writing mostly from memory back from 2-3 years ago when it wasn't the case.

**Comment by jjkeijser** [comment]
ppp 2.4.9 was released on January 5th 2021, so this has been in there for a little over 2 years now.  Could be that my older eap-tls patches also included this functionality, but I haven't checked.
Please retest and provide more details about software versions and possible distro-specific patches.

**Comment by enaess** [comment]
@jjkeijser Some of this code was consolidated with the merge of PEAP support. It's now located in tls.c

```
int tls_set_version(SSL_CTX *ctx, const char *max_version)
{
#if defined(TLS1_2_VERSION)
    long tls_version = TLS1_2_VERSION; 
#elif defined(TLS1_1_VERSION)
    long tls_version = TLS1_1_VERSION; 
#else
    long tls_version = TLS1_VERSION; 
#endif

    /* As EAP-TLS+TLSv1.3 is highly experimental we offer the user a chance to override */
    if (max_version) {
        if (strncmp(max_version, "1.0", 3) == 0) {
            tls_version = TLS1_VERSION;
        }
        else if (strncmp(max_version, "1.1", 3) == 0) {
            tls_version = TLS1_1_VERSION;
        }
        else if (strncmp(max_version, "1.2", 3) == 0) {
#ifdef TLS1_2_VERSION
            tls_version = TLS1_2_VERSION;
#else
            warn("TLSv1.2 not available. Defaulting to TLSv1.1");
            tls_version = TLS_1_1_VERSION;
#endif
        }
        else if (strncmp(max_version, "1.3", 3) == 0) {
#ifdef TLS1_3_VERSION
            tls_version = TLS1_3_VERSION;
#else
            warn("TLSv1.3 not available.");
#endif
        }
    }   

    dbglog("Setting max protocol version to 0x%X", tls_version);
    if (!SSL_CTX_set_max_proto_version(ctx, tls_version)) {
        error("Could not set max protocol version");
        return -1; 
    }   

    return 0;
}
```

If I am reading this right, we are setting the TLS version 1.2 by default, and then let users specify `max-tls-version` to a number lesser than 1.2, e.g. 1.0, 1.1, 1.2, or 1.3. However, because the initial value of tls_version is set to 1.2, one would need to specify `max-tls-version` to "1.3" for pppd to actually set the TLS version to 1.3. Probably, should allow it to be initially set to 1.3? -- IDK

**Comment by Neustradamus** [comment]
Please look it before 1.5.0...

cc: @paulusmack.

**Comment by jjkeijser** [comment]
support for `max-tls-version` was present in my EAP-TLS patch 1.301 from may 2020 and the basic mechanism behind it has not changed - so I would expect that the current behaviour was also present in patch 1.301.

As for the default begint TLSv1.2 and not 1.3 ? that is because I was never able to test it against a client that requested or requested TLS v1.3 other than the (patched) `pppd` code itself. Thus I have no idea if TLSv1.3 support is implemented correctly (nor was there an RFC at the time).  I would strongly recommend to leave the default at TLSv1.2 and offer v1.3 only as an *experimental* (i.e use at your own risk ) feature.

@Neustradamus  I have no idea what you mean by 1.5.0

**Comment by Evengard** [comment]
I just retested my setup, seems like the downgrade works just fine. Honestly, have no ideas why it bugged before, seems to be OK now, maybe got fixed. Closing.

**Comment by enaess** [comment]
@jjkeijser I think @Neustradamus meant 2.5.0 as in the next upcoming release of pppd

**Comment by Neustradamus** [comment]
Yes, 2.5.0!
