### ISSUE TITLE
cppcheck: assorted findings "known condition true or false"

### ISSUE THREAD

**Issue by chipitsine** [ppp-project/ppp#389]
```
common/zlib.c:3839:13: style: Condition 't<19' is always false [knownConditionTrueFalse]
modules/ppp.c:1502:14: style: Condition 'pass<0' is always false [knownConditionTrueFalse]
modules/ppp.c:1509:16: style: Condition 'pass' is always true [knownConditionTrueFalse]
pppd/auth.c:712:9: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/auth.c:723:20: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/auth.c:740:9: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/auth.c:780:9: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/auth.c:827:9: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/crypto.c:491:9: style: Condition '!PPP_crypto_deinit()' is always false [knownConditionTrueFalse]
pppd/main.c:316:9: style: Condition 'ifname' is always true [knownConditionTrueFalse]
pppd/main.c:1198:22: style: Condition 'error_count!=errs' is always false [knownConditionTrueFalse]
pppd/main.c:1216:22: style: Condition 'error_count!=errs' is always false [knownConditionTrueFalse]
pppd/main.c:1244:9: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/plugins/radius/config.c:207:42: style: Condition '*p=='\0'' is always false [knownConditionTrueFalse]
pppd/plugins/radius/radius.c:748:25: style: Same expression on both sides of '&&' because 'mppe_enc_policy' and 'mppe_enc_keys' represent the same value. [knownConditionTrueFalse]
pppd/sys-linux.c:803:13: style: Condition '!mp_on()' is always true [knownConditionTrueFalse]
pppd/sys-linux.c:3557:13: style: Condition 'sfd<0' is always true [knownConditionTrueFalse]
pppdump/zlib.c:3368:13: style: Condition 't<19' is always false [knownConditionTrueFalse]
solaris/ppp.c:1515:14: style: Condition 'pass<0' is always false [knownConditionTrueFalse]
solaris/ppp.c:1522:16: style: Condition 'pass' is always true [knownConditionTrueFalse]
```

**Comment by paulusmack** [comment]
Many of these seem to be config-dependent, that is, the condition might be always true or always false in a particular configuration of the software but not in other configurations. For example, mp_on() is always false if multilink is not enabled, but may be either true or false when multilink is enabled.

**Comment by paulusmack** [comment]
@enaess: in ppp_set_ifname(), did you mean to test 'name' (the function parameter) rather than 'ifname', which is a static array?

**Comment by paulusmack** [comment]
pppd/main.c:1198:22: style: Condition 'error_count!=errs' is always false [knownConditionTrueFalse]
pppd/main.c:1216:22: style: Condition 'error_count!=errs' is always false [knownConditionTrueFalse]

These ones appear to be just plain wrong. error_count is a global and can be changed by the function call that occurs between the two reads of error_count.

**Comment by paulusmack** [comment]
pppd/plugins/radius/config.c:207:42: style: Condition '*p=='\0'' is always false [knownConditionTrueFalse]

One has to know the semantics of fgets() to know that it's always false; and if that test was removed, and for some reason fgets() did ever return an empty string, then a couple of lines further on we would be doing buffer[-1] = 0, which might perhaps be exploitable. I'd rather than the code was visibly avoiding doing buffer[-1] = 0.

**Comment by paulusmack** [comment]
pppd/plugins/radius/radius.c:748:25: style: Same expression on both sides of '&&' because 'mppe_enc_policy' and 'mppe_enc_keys' represent the same value. [knownConditionTrueFalse]

This also appears to be incorrect (or possibly config-dependent, if you have assumed that PPP_WITH_MPPE is not defined, but in that case line 748 would not have been compiled in). mppe_enc_policy and mppe_enc_keys are different variables set by different branches of the switch statement at line 665 of radius.c.

**Comment by paulusmack** [comment]
pppd/sys-linux.c:3557:13: style: Condition 'sfd<0' is always true [knownConditionTrueFalse]

Only if you assume TIOCGPTN is not defined. Glibc (at least) defines it.

**Comment by Neustradamus** [comment]
@chipitsine: https://github.com/ppp-project/ppp/pull/396 has been merged, it is good?

**Comment by chipitsine** [comment]
this particular finding is resolved 

`pppd/main.c:316:9: style: Condition 'ifname' is always true [knownConditionTrueFalse]`

as for remaining findings, if them are not going to be addressed, I think issue can be closed

**Comment by enaess** [comment]
@chipitsine Can this be closed now?
