### ISSUE TITLE
Permission to use Public Domain license

### ISSUE THREAD

**Issue by PoonamPJadhav** [ppp-project/ppp#474]
Hi,

ppp package has chat, chatchat.c & sha1.c are in Public Domain. The term "Public Domain" does not exist in our (European/German) jurisdiction. 
We wanted to get permission from author to use the corresponding software and to distribute it with our (commercial) products, modification if needed in public domain license for softwares. Brief information about what author means/understands the public domain is needed.
cc @paulusmack 

Thanks

**Comment by paulusmack** [comment]
My understanding is that by saying that the software is in the public domain, the original author has disclaimed any rights with respect to the program that copyright law would otherwise give them. Hence, anyone can use it in any manner they please.

I will consider putting a copyright notice on those files saying something like "This version copyright 2024 Paul Mackerras <paulus@ozlabs.org>" with a 2-clause BSD licence, just to give users such as yourself a concrete set of licence conditions for certainty. Would that help?

**Comment by Neustradamus** [comment]
@paulusmack: If you add, please add the initial year project and 2024 -> XXXX-2024

**Comment by Neustradamus** [comment]
About Public domain in EU:
- https://intellectual-property-helpdesk.ec.europa.eu/news-events/news/public-domain-2020-11-19_en

**Comment by paulusmack** [comment]
> @paulusmack: If you add, please add the initial year project and 2024 -> XXXX-2024

What do you mean by "initial year project"?

Anyway, a copyright notice doesn't have to have a range of dates.

**Comment by paulusmack** [comment]
For chat.c, d0c04daa278b adds a copyright notice with MIT licence permissions (one of the most permissive licence statements that I know of). For the others, sha1.c is no longer included, and I just removed scripts/chatchat.c as I don't want to maintain it.
